// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwacxqxorhnzzpbpwura.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YWN4cXhvcmhuenpwYnB3dXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NTQwMDIsImV4cCI6MjA2NzUzMDAwMn0.sn7eZ1uVRuNdR6n9jN9SgFS4qpLqS-l1r7OHb_GdLyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});